---
title: "Topo StatMed"
output:
  html_document:
    theme: journal
    highlight: monochrome
    css: style.css
---

## Installation (à faire avant la séance pour gagner du temps) 

Il est indispensable d'installer [R](https://cran.r-project.org/) et [Rstudio](https://posit.co/download/rstudio-desktop/) dans cet ordre. Il est important de respecter l'ordre d'installation et n'utiliser que ces versions issues des plateformes officielles des contributeurs.

## Bases de données 

[Heart disease database](http://masedki.github.io/datasets/heart_disease.csv)

[Jeu de données d'oncologie](http://masedki.github.io/formations/datasets/TroisCancers.rda)

## Code R utilisé en première session 

[Code R à exécuter pour se familiariser avec les commandes R](http://masedki.github.io/formations/rcode/r_database_demo.R)

## Aide et commandes R

 - [Commandes R](http://masedki.github.io/formations/pdfs/commandes_r.pdf) mémoire du Dr Julien Chiquet (DR Inrae)
 
 
## Supports des présentations 

- [StatMed](http://masedki.github.io/formations/pdfs/statmed.pdf) 
 
<!-- - [Livre : analyse de survie appliquée avec R](http://masedki.github.io/formations/pdfs/survival_analysis_book.pdf)  -->

- [Livre : analyse de survie appliquée avec R](https://link.springer.com/book/10.1007/978-3-319-31245-3) 

- [Mine d'or 1](https://stackoverflow.com/) pour trouver des astuces et solutions de programmation avec R

- [Mine d'or 2](https://stats.stackexchange.com/) pour trouver des réponses à vos questions en stats 
 

Si vous avez des questions, n'hésitez pas à m'écrire à mon adresse mail disponible sur la [page principale](masedki.github.io). Parfois le navigateur bloque le téléchargement du code R, n'oubliez pas de confirmer le téléchargement. 
