---
title: "Python"
output:
  html_document:
    theme: journal
    highlight: monochrome
    css: style.css
---


## à installer 

Télécharger et installer anaconda [ici](https://www.anaconda.com/) 

Télécharger et installer Visual Studio Code [ici](https://code.visualstudio.com/) 

## séance d'introduction

[Types de données de base](http://masedki.github.io/enseignements/python/typesdonnees.html)

[Contrôle de flux et boucles](http://masedki.github.io/enseignements/python/loopflowcontrol.html)

[Fonctions](http://masedki.github.io/enseignements/python/functions.html)

[Design orienté-object](http://masedki.github.io/enseignements/python/Object_oriented_design.html)

[Compilé versus interprété](http://masedki.github.io/enseignements/python/Compiled_and_interpreted.html)

[Tableaux et matrices](http://masedki.github.io/enseignements/python/arraymatrix.html)

[Module math de base](http://masedki.github.io/enseignements/python/basicmath.html)


<!-- [Introduction](http://masedki.github.io/enseignements/python/Nb1-IntroPython.html) -->

<!-- [(correction)](http://masedki.github.io/enseignements/python/exercices_correction.html) -->

[Trafic de données avec pandas](http://masedki.github.io/enseignements/python/Nb2-PythonPandas.html)

[Graphiques](http://masedki.github.io/enseignements/python/graphics.html)

[Probabilités et statistiques](http://masedki.github.io/enseignements/python/probasstats.html)

[exercices](http://masedki.github.io/enseignements/python/exercices.html) 

<!-- [+solutions](http://masedki.github.io/enseignements/python/exercices_correction.html) -->
<!-- [Devoir 2022](http://masedki.github.io/enseignements/python/devoir_2022.pdf) -->


### Travaux pratiques

[Création d'une classe ](http://masedki.github.io/enseignements/python/class_logisticregression.html)
[ + document d'explication](http://masedki.github.io/enseignements/pdfs/python/tp_logistic.pdf) 
[ + correction](http://masedki.github.io/enseignements/python/class_logisticregression_sol.html)

[classification par les knn (corrigé)](http://masedki.github.io/enseignements/python/knn_mixture.html)



### Instruction pour lancer jupyter notebook sur un environnement virtuel en ligne de commande


`python -m ipykernel install --user --name=myenv`

<!-- ### Jeux de données  -->

<!-- [jeu de données coronary](http://masedki.github.io/enseignements/datasets/coronary.csv) -->

<!-- [jeu de données Titanic](http://masedki.github.io/enseignements/datasets/titanic-train.csv) -->

[jeu de données mixture](http://masedki.github.io/enseignements/datasets/mixture.txt)



<!-- ## Devoir 2024 -->

<!-- Le devoir est disponible [ici](http://masedki.github.io/enseignements/pdfs/python/devoir_python_2024.pdf).  -->

<!-- Le format à rendre est sous forme d'un pdf (```prenom_nom.pdf```) généré à partir d'un jupyter notebook avec les sorties des calculs. Sans les sorties des différentes cellules du notebook, la réponse ne sera pas prise en compte.  -->

[Image à télécharger ](http://masedki.github.io/enseignements/datasets/irm_small.jpeg)

## Examens des deux années précédentes 


[Examen 2023/2024](http://masedki.github.io/enseignements/pdfs/python/examen_2024.pdf)


[Examen 2024/2025](http://masedki.github.io/enseignements/pdfs/python/examen_2025.pdf)


<!-- [+ correction+solutions des exercices racine carrée et jour de naissance](http://masedki.github.io/enseignements/python/proposition_de_correction_2024.html) -->




## Devoir 2025

Il est indispensable de lire et comprendre la partie 9.3.3 voire tout le chapitre 9 du livre de Bishop disponible [ici](http://masedki.github.io/enseignements/pdfs/python/Bishop_PRML.pdf) pour la réalisation du devoir.  Le devoir est disponible [ici](http://masedki.github.io/enseignements/pdfs/python/devoir_python_2526.pdf). Vous pouvez travailler en binôme ou individuellement.

Le format à rendre est sous forme d'un pdf (```prenom_nom.pdf``` ou ```prenom1_nom1_prenom2_nom2.pdf``` pour un binôme) généré à partir d'un jupyter notebook avec les sorties des calculs. Sans les sorties des différentes cellules du notebook, la réponse ne sera pas prise en compte.


[Poly de classification non supervisée](http://masedki.github.io/enseignements/pdfs/python/ClassificationNonSupervisee.pdf)