---
title: "Présentation des données TPretinol"
author: "Therese Stukel, Dartmouth Hitchcock Medical Center 
         One Medical Center Dr. Lebanon, NH 03756"
date: ""
output:
  html_document: default
  pdf_document: default
fontsize: 12pt
---

Le jeu de données est disponible [ici](https://masedki.github.io/presentationTPretinol.csv). Voici, en résumé et en anglais, la présentation de l'étude proposée par les auteurs : 

*Observational studies have suggested that low dietary intake or low plasma concentrations of retinol, beta-carotene, or other carotenoids might be associated with increased risk of developing certain types of cancer. However, relatively few studies have investigated the determinants of plasma concentrations of these micronutrients. We designed a cross-sectional study to investigate the relationship between personal characteristics and dietary factors, and plasma concentrations of retinol, beta-carotene and other carotenoids. Study subjects (N = 315) were patients who had an elective surgical procedure during a three-year period to biopsy or remove a lesion of the lung, colon, breast, skin, ovary or uterus that was found to be non-cancerous. We display the data for only two of the analytes.*

## Intitulés des variables : 

- AGE : Age (en années).
- SEXE : 1=Masculin, 2=Féminin.
- TABAC : 1=jamais, 2=autrefois, 3=actuellement.
- BMI : poids/(taille^2).
- VITAMINES : 1=oui, souvent, 2=oui, pas souvent, 3=non.
- CALORIES : Nombre de calories par jour.
- GRAISSES : Grammes de graisse consommés par jour.
- FIBRES : Grammes de fibre consommés par jour.
- ALCOOL : Nombre de verres d'alcool consommés par semaine.
- CHOLESTEROL : Cholesterol consommé (mg par jour).
- BETADIET : beta-carotene consommé (mcg par jour).
- RETDIET : retinol consommé (mcg par jour).
- BETAPLASMA : beta-carotene plasmatique (ng/ml).
- RETPLASMA : Retinol plasmatique (ng/ml).