---
title: '**Publications **'
output:
  html_document: default
  pdf_document: default
---

* **Marbac, M., Sedki, M., Biernacki, C., and Vandewalle, V.** [Simultaneous semi-parametric estimation of clustering and regression](https://doi.org/10.1080/10618600.2021.2000872) *Journal of Computational and Graphical Statistics*, Accepted (2021), 

* **Dumas, O., Bédard, A., Marbac, M., Sedki, M., Temam, S., Chanoine, S., Severi, G., Boutron-Ruault, M.-C., Garcia-Aymerich, J., Siroux, V., et al.** [Household cleaning and poor asthma control among elderly women](https://doi.org/10.1016/j.jaip.2021.02.022)  *The Journal of Allergy and Clinical Immunology: In Practice*, Volume 9, Issue 6  (2021), 2358–2365

* **Saldanha-Gomes, C., Marbac, M., Sedki, M., Cornet, M., Plancoulaine, S., Charles, M.-A., Lioret, S., and Dargent-Molina, P** [Clusters of diet, physical activity, television exposure and sleep habits and their association with adiposity in preschool children: the eden mother-child cohort](https://doi.org/10.1186/s12966-020-00927-6)  *International Journal of Behavioral Nutrition and Physical Activity*, Volume 17, Issue (1) (2020), 1–13


* **Marin, J-M and Pudlo, P and Sedki, M** [Consistency of Adaptive Importance Sampling and Recycling Schemes](https://projecteuclid.org/euclid.bj/1560326434) *Bernoulli*, Volume 25, Number 3 (2019), 1977-1998


* **Marin, J-M and Pudlo, P and Sedki, M** [Consistency of Adaptive Importance Sampling and Recycling Schemes](https://projecteuclid.org/euclid.bj/1560326434) *Bernoulli*, Volume 25, Number 3 (2019), 1977-1998

* **Marbac, M and Patin, E and Sedki, M** [Variable selection for mixed data clustering: Application in human population genomics](https://link.springer.com/article/10.1007/s00357-018-9301-y), *Journal of Classification* 

* **Pudlo, P and Sedki, M** [Simulation of stochastic models of structured
population in population genetics under neutrality](http://journal-sfds.fr/article/view/707)  *Journal de la SFDS*, Special Issue on Models and Inference in Population Genetics, Vol. 159 No 3 (2018) 

* **Marbac, M and Sedki, M** [VarSelLCM: an R/C ++ package for variable selection in model-based clustering of mixed-data with missing values](https://doi.org/10.1093/bioinformatics/bty786), *Bioinformatics*, First Online: September 05, 2018 

* **Marbac M; Sedki, M; Boutron-Ruault, M-C; Dumas, O** [Patterns of cleaning product exposures using a novel clustering approach for data with correlated variables](https://doi.org/10.1016/j.annepidem.2018.05.004) *Annals of Epidemiology*, Volume:28, Issue:8, August 2018, pp:563-569 

* **Celeux, G and Maugis-Rabusseau, C and Sedki, M** [Variable selection in model-based clustering and discriminant analysis with a regularization approach](https://doi.org/10.1007/s11634-018-0322-5) *Advances in Data Analysis and Classification*, First Online: 11 April 2018, pp:1-20

* **Marbac M and Sedki, M** [A family of block-wise one-factor distributions for modeling high-dimensional binary data](https://doi.org/10.1016/j.csda.2017.04.010) *Computational Statistics and Data Analysis*,  Volume:114, October 2017, pp:130-145

* **Marbac M and Sedki, M** [Variable selection for model-based clustering using the integrated complete-data likelihood](https://doi.org/10.1007/s11222-016-9670-1) *Statistics and Computing*,  Volume:27, Issue:4, July 2017, pp:1049–1063 

* **Marbac, M and Tubert-Bitter, P and Sedki, M** [Bayesian model selection in logistic regression for the detection of adverse drug reactions](https://doi.org/10.1002/bimj.201500098) *Biometrical Journal*, Volume:58, Issue:6, November 2016, pp:1376-1389 

* **Ribatet, M and Sedki, M** [Extreme value copulas and max-stable processes](http://journal-sfds.math.cnrs.fr/index.php/J-SFdS/article/view/160)  Vol. 154 No 1 (2013): Numéro spécial sur les copules du *Journal de la SFDS* 

* **Andrieu, C; Barthelme, S; Chopin, N; Cornebise, J; Doucet, A; Girolami, M; Kosmidis, I; Jasra, A; Lee, A; Marin, J-M; Pudlo, P; Robert, CP; Sedki, M; Singh, SS** [Some discussions of D. Fearnhead and D. Prangle's Read Paper" Constructing summary statistics for approximate Bayesian computation: semi-automatic approximate Bayesian computation"](https://doi.org/10.1111/j.1467-9868.2011.01010.x) *Journal of the Royal Statistical Society (series B)*, Volume:74, Issue:3, June 2012, pp:419-474

* **Marin, J-M and Pudlo, P and Sedki, M** [Optimal parallelization of a sequential approximate Bayesian computation algorithm](https://doi.org/10.1109/WSC.2012.6465244) *Proceedings of the Winter Simulation Conference*,9-12 Dec. 2012